version: '3'
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A4@database
    ports:
        - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  app:
    image: book_recommendation_app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my-database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: A4@database

